travis:
  secure:
    BINSTAR_TOKEN: XbEVYXWkWW3TNQtmBJ8WKbDRhtREhLi/7Uk5ixrLbtQVlDU7Ha8iNXqjFaf5GjpCiP9BjyS/mX/aEeVoxeXXePG+txskCWS375idf4RhZRn3X0CQ2SLQuc581KYuKrhHcR8KiB3oGLdyAPWUzyAERC0NcKgMaCKbEPKNjqABiGheze7y2lJH4GWmvj2zWX8fSPoPH/9nIFEvUO1DMrAsvTQkMnq2Q+m0sj+VUH83SD9udP8RNxCxIFB089wK1sE8ZAPpuQwDM+JNSgh4YDck96xKbHD4gq0h1U5XL97KGTfH9T83Im/JvX3kBMYKMT2fPqgtEsGMxHPzrSkUJP3OVKFblTAb9593HYNspKfqNkzn//Xd/vkqFA3sP1P0651UZhlxqbnraGCGqOp4UdiyWuerkzm2s/+fPO+CI+fE5oDRfzy2R9fM19Fn3JnzhmZE/MmCcx5CYLuflmWL4dKrbifbzJUfCToj/kdC7rl2P1xO+RIYHLA352V1bklDuQx8BBnI5+HwMGeFoEIchnBQhCOLk86XVD7gsPQPIlSPpm3CizpPUIGxV+qmRA9YULYtPJ1lxXbxTuBM8N49co+GHM4FD3m/GGQWZcZbJko3yHQCyT2TPf2QcOg737kgG622iB0FIi3ip+6j3i1dA9gToIQL2N06YHmGeEvsRgs4hbg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
