travis:
  secure:
    BINSTAR_TOKEN: Oy0x46aF8boKhTHQ8Svk/ttcDmIaNOC2D8c+lO1Tv28sGDod0jcAkT0OPR3h1zdN2XE5z4Pk+s6Vwun1kV6CRis6qDX/FS/qN/bz/X/Td7DYUWHwNX2AEneAndbUHuv0IGREENDJceNLA6tFmv6brHzpRtLjEvNXZ8ktxj1s/X/bavomugRgQVOjwMzwSeZFjykYRpV4Oasg5gFwxd5uSVWK8F9hoTnrGxrX/0afXGqERTtrjj/dXx2FQBolx2BBhhPteeNkYQSsWGERBlYkUeCuyxFVjpVo6z6nDV0LhDPVKs6xbetHRLJlXht+LJ+MSlhJ6p0uiDLyzDuB1h9LoIrVb8bSkslBGBcQq+1F1JiMY+9/QmuZygyeCVUyz9kijyUVdTvKT16QTqPGIUHApLqY5+Pb8tdhg2PH5MIJyRFHAOGRSENYdRVEK9x+udUVw73VkBobipLie6Cx5WP6tEN/1C5YfONf5BZUAkM7HIaC7OWiz80c7V4E6b/B1lx1lcnyDSi6him2FpmnTL4xfFHxxsaL0t1bhlSxSg2ZLjA8KfCboOMbW67r8RGpBPc0erAtT+osjQDSfBcEe8w7iSjZgAuRJf17ozKD6BQa0ZYPxwPW/Mg1Ra94aDvne8Cllj0TZAaut/0aS/8iiJhne953JdbJ6JfaAeEDtXU2OlA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
